### ISSUE TITLE
Consider transferring to haskell-perf

### ISSUE THREAD

**Issue by ocramz** [4e6/haskell-perf-xml#2]
This is a GH organization devoted to performance benchmarks:

https://github.com/haskell-perf

I'm sure the owner, @chrisdone , would be happy to add you to it and feature the library there.

**Comment by chrisdone** [comment]
Good idea. It looks like it copies the basic haskell-perf template anyway so it would fit well there. @4e6 I'll add you to the haskell-perf organization and you can transfer it under the name `xml` if you like. 👍

**Comment by 4e6** [comment]
Thank you, I'm glad to contribute.

Transferring is complete. I wanted to transfer and then rename but should've done it in the different order. @chrisdone please rename it to `xml` because I don't have access to the settings anymore.

**Comment by chrisdone** [comment]
I’ll fix that so you have full access properly.

**Comment by chrisdone** [comment]
Changed you to an admin on that project!
